#!/usr/bin/bash -ex

export PATH=/cygdrive/c/Program\ Files\ \(x86\)/Java/jdk1.8.0_131/bin:`pwd`:$PATH

rm -rf base
./apktool.bat if framework-res.apk
./apktool.bat if base.apk
./apktool.bat d -t --keep-broken-resources base.apk
#mv base/res/drawable-hdpi-v4/tygem.PNG base/res/drawable-hdpi-v4/tygem.png
#convert base/res/drawable-xhdpi-v4/btn_off.png base/res/drawable-xhdpi-v4/btn_off.jpg
#convert base/res/drawable-xhdpi-v4/btn_off.jpg base/res/drawable-xhdpi-v4/btn_off.png
convert base/res/drawable-xhdpi-v4/toggle_off.png base/res/drawable-xhdpi-v4/toggle_off.jpg
convert base/res/drawable-xhdpi-v4/toggle_off.jpg base/res/drawable-xhdpi-v4/toggle_off.png
rm base/res/drawable-xhdpi-v4/*.jpg
cp base/res/values/strings.xml strings.xml.orig
cp strings.xml base/res/values-en/strings.xml
cp gwanlist_btn_normal.png base/res/drawable-xhdpi-v4/gwanlist_btn_normal.png
cp gwanlist_btn_pressed.png base/res/drawable-xhdpi-v4/gwanlist_btn_pressed.png
for i in `grep -lr MS949 base`; do sed -i s/MS949/MS932/g $i; done
./apktool.bat b base

rm -f debug.keystore
keytool -genkey -v -keystore debug.keystore -alias android -keyalg RSA -keysize 2048 -validity 20000
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore debug.keystore base/dist/base.apk android

mkdir -p output/
rm -f output/base.apk
./zipalign.exe -v 4 base/dist/base.apk output/base.apk
